const TEST_REQUEST = 'TEST_REQUEST';
const TEST_REQUEST_SUCCESS = 'TEST_REQUEST_SUCCESS';
const TEST_REQUEST_FAILED = 'TEST_REQUEST_FAILED';

export default {
  TEST_REQUEST,
  TEST_REQUEST_FAILED,
  TEST_REQUEST_SUCCESS,
}