const TEST_REQUEST = 'TEST_REQUEST';
const TEST_REQUEST_SUCCESS = 'TEST_REQUEST_SUCCESS';
const TEST_REQUEST_FAILED = 'TEST_REQUEST_FAILED';

const LOGIN = 'LOGIN';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
const LOGIN_FAILED = 'LOGIN_FAILED';

const LOGOUT = 'LOGOUT';
const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
const LOGOUT_FAILED = 'LOGOUT_FAILED';

const CHECK_LOCAL_STORAGE = 'CHECK_LOCAL_STORAGE';
const CHECK_LOCAL_STORAGE_SUCCESS = 'CHECK_LOCAL_STORAGE_SUCCESS';
const CHECK_LOCAL_STORAGE_FAILED = 'CHECK_LOCAL_STORAGE_FAILED';

export default {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAILED,
  LOGOUT,
  LOGOUT_SUCCESS,
  LOGOUT_FAILED,
  CHECK_LOCAL_STORAGE,
  CHECK_LOCAL_STORAGE_SUCCESS,
  CHECK_LOCAL_STORAGE_FAILED,
  TEST_REQUEST,
  TEST_REQUEST_FAILED,
  TEST_REQUEST_SUCCESS,
};