export default {
  INCREMENT: 'INCREMENT',
  DECREMENT: 'DECREMENT',
  REQUEST_GET_USER: 'REQUEST_GET_USER',
  REQUEST_GET_USER_SUCCESS: 'REQUEST_GET_USER_SUCCESS',
  REQUEST_GET_USER_FAILED: 'REQUEST_GET_USER_FAILED',
}